[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "daqpytools"
requires-python = ">=3.10"
readme = "docs/README.md"
version = "0.1.0"
description = "Description left as an exercise for the developer."
dependencies = [
    "click==8.1.7",
    "kafka-python==2.0.2",
    "pytz==2024.2",
    "rich==13.9.4",
    "sh==2.1.0",
]
[tool.setuptools]
package-dir = {"" = "src"}

[project.optional-dependencies]
dev = [
    "ruff",
    "pre-commit",
    "pytest",
    "isort",
    "black",
    "pytest-cov",
    "pytest-mypy",
    "taplo"
]

[project.scripts]
daqpytools-logging-demonstrator = "daqpytools.apps.__main_logging_demonstrator__:main"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "D",
    "E",
    "F",
    "I",
    "UP",
    "RUF","ANN"
]
ignore = [
    "D205",
    "D100",
    "D104"
]
pydocstyle.convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "D100",
    "D103",
    "D104",
    "S101",
    "ANN201"
]

[tool.black]
line-length = 88
target-version = ["py310", "py311", "py312", "py313"]
skip-magic-trailing-comma = true
force-exclude = '''
/(
    \.git
  | \.github
  | \.ruff_cache
)/
'''

[tool.mypy]
ignore_missing_imports = true
mypy_path = "src"

[tool.pytest.ini_options]
# addopts = "-v --mypy -p no:warnings --cov=. --cov-report=html --doctest-modules --ignore=manage.py --ignore=drunc_ui/settings/ --ignore=docs/ --ignore=example_deployment/ --ignore=ers/"
# DJANGO_SETTINGS_MODULE = "drunc_ui.settings"
# FAIL_INVALID_TEMPLATE_VARS = true
# testpaths = ["tests"]
# norecursedirs = [".git", ".github", "venv", "src"]

[tool.coverage.run]
omit = ["tests/*", "scripts/*"]