[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "daqpytools"
requires-python = ">=3.10"
readme = "docs/README.md"
dynamic = ["version"]
description = "Description left as an exercise for the developer."

[project.optional-dependencies]
dev = [
    "ruff",
    "pre-commit",
    "pytest",
    "isort",
    "black",
    "pytest-cov",
    "pytest-mypy", # TODO
    "taplo"
]

[tool.hatch.version]
path = "version.py"

[tool.hatch.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "D",
    "E",
    "F",
    "I",
    "UP",
    "RUF","ANN"
]
ignore = [
    "D205",
    "D100",
    "D104"
]
pydocstyle.convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "D100",
    "D103",
    "D104",
    "S101",
    "ANN201"
]

[tool.black]
line-length = 88
target-version = ["py310", "py311", "py312", "py313"]
skip-magic-trailing-comma = true
force-exclude = '''
/(
    \.git
  | \.github
  | \.ruff_cache
)/
'''

[mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
# addopts = "-v --mypy -p no:warnings --cov=. --cov-report=html --doctest-modules --ignore=manage.py --ignore=drunc_ui/settings/ --ignore=docs/ --ignore=example_deployment/ --ignore=ers/"
# DJANGO_SETTINGS_MODULE = "drunc_ui.settings"
# FAIL_INVALID_TEMPLATE_VARS = true
# testpaths = ["tests"]
# norecursedirs = [".git", ".github", "venv", "src"]

[tool.coverage.run]
omit = ["tests/*", "scripts/*"]